[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  AUTH_URL = "https://elaborate-mochi-fbcbb9.netlify.app"
  CLIENTS_URL = "https://remarkable-meringue-a5de53.netlify.app"
  DEALS_URL = "https://dashing-mousse-c8cc33.netlify.app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
